--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/HmmHmmmm/ShopPlugin
build-by-default: true
branches:
- master
projects:
  ShopPlugin:
    path: ""
    icon: "images/icon.png"
    libs:
    - src: jojoe77777/FormAPI/libFormAPI
      version: ^1.3
    - src: muqsit/InvMenu/InvMenu
        version: 3.1.0
...
